version: '3'

services:
  secexlog_mysql:
    image: mysql
    container_name: secexlog_mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: secexlog
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network

  secexlog_adminer:
    image: adminer
    container_name: secexlog_adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  secexlog_redis:
    image: redis
    container_name: secexlog_redis
    command: redis-server --requirepass redis
    ports:
      - 6379:6379

networks:
  mysql-compose-network:
    driver: bridge
