version: '3'

services:
  mysql:
    image: mysql
    container_name: secexlog_mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: secexlog
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: secexlog_adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  redis:
    image: redis
    container_name: secexlog_redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  db_data:
    driver: local
